default: &default
  user: <%= Rails.application.secrets['fedora']['user'] %>
  password: <%= Rails.application.secrets['fedora']['password'] %>
  url: <%= Rails.application.secrets['fedora']['url'] %>
  base_path: <%= Rails.application.secrets['fedora']['base_path'] %>

development:
  <<: *default
test:
  <<: *default
  <%= 'url: http://localhost:8983/fedora/rest' if ENV['TRAVIS'] %>
production:
  <<: *default
