default: &default
  host: <%= Rails.application.secrets['redis']['host'] %>
  port: <%= Rails.application.secrets['redis']['port'] %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
